version: '3.1'
services:
    db{{.Task.Slot}}:
      image: cockroachdb/cockroach:v1.0.2
      deploy:
            mode: replicated
            replicas: 3
      ports:
            - 8888:8080
      command: start --advertise-host=cockroach_db1 --logtostderr --insecure
      networks:
            - cockroachdb
      volumes:
            - cockroach-db{{.Task.Slot}}:/cockroach/cockroach-data
    crdb-proxy:
      image: jowings/crdb-proxy:v1
      deploy:
         mode: replicated
         replicas: 1
      ports:
         - 26257:26257
      networks:
         - cockroachdb

networks:
    cockroachdb:
        external: true

volumes:
    cockroachdb-1:
      driver: pure
      driver_opts:
         size: 100GiB
    cockroachdb-2:
      driver: pure
      driver_opts:
         size: 100GiB
    cockroachdb-3:
      driver: pure
      driver_opts:
         size: 100GiB
